language: python
matrix:
    include:
        - python: 3.6
        # Travis does not ship with 3.7 so have to install it.
        - python: 3.7
          dist: xenial
          sudo: true
before_install:
    - sudo apt-get update
    - sudo apt-get install -y mercurial subversion
    - pip install tox-travis
script: tox
