language: python
matrix:
    include:
        - python: 3.6
        # Travis does not ship with 3.7 so have to install it.
        - python: 3.7
          dist: xenial
          sudo: true
        # Testing Python 3 on OS X is a pain.
        - language: generic
          python: 3.6
          os: osx
before_install:
    - ./before_install.sh
script: tox
